2024-03-24 17:01:00 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[chromium] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjM3NjM3NDk3ODAwOTg3ODM1NzE=' 
-d ''
2024-03-24 17:01:36 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[chromium] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:l0Cvt3ZkR7G' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:e1e670b6-0985-45a3-8bb7-b4157f4329f4'
-H 'Cookie:TCSESSIONID=8A4D42D0E04A40CCAC21ECFFA04E7645'
-H 'Content-Length:0'
-H 'Authorization:Basic OjM3NjM3NDk3ODAwOTg3ODM1NzE=' 
-d '' 
 

2024-03-24 17:01:36 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:l0Cvt3ZkR7G'. Project cannot be found by external id 'l0Cvt3ZkR7G'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m