2024-03-24 17:43:37 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[chromium] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjE4NjM1NjE1MjY2MTAwMzczNDE=' 
-d ''
2024-03-24 17:44:12 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[chromium] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:GWjJykDsI77' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:dc7959a8-8ac5-42c1-9b24-0b43c70457a8'
-H 'Cookie:TCSESSIONID=92E3EF8272161BD9B10EE8238DBEE1E7'
-H 'Content-Length:0'
-H 'Authorization:Basic OjE4NjM1NjE1MjY2MTAwMzczNDE=' 
-d '' 
 

2024-03-24 17:44:12 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:GWjJykDsI77'. Project cannot be found by external id 'GWjJykDsI77'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m