2024-03-24 17:43:40 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[webkit] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjE4NjM1NjE1MjY2MTAwMzczNDE=' 
-d ''
2024-03-24 17:44:15 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[webkit] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:FD3sqRFthVw' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:1a0ed65b-8285-43c5-b4f6-ee2f1a14e409'
-H 'Cookie:TCSESSIONID=FCDBC06B240859BE836545712F0BAAC1'
-H 'Content-Length:0'
-H 'Authorization:Basic OjE4NjM1NjE1MjY2MTAwMzczNDE=' 
-d '' 
 

2024-03-24 17:44:15 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:FD3sqRFthVw'. Project cannot be found by external id 'FD3sqRFthVw'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m