2024-03-24 17:15:44 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[chromium] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjgzNzY4MDc3NzA5MDE0NDM3MzE=' 
-d ''
2024-03-24 17:16:21 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[chromium] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:b3p2ivXMHB9' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:bb781064-83b9-4f45-bce9-3a0d008e2fa8'
-H 'Cookie:TCSESSIONID=5E6E3CEC6B9107C8C90583BC1CEDB70C'
-H 'Content-Length:0'
-H 'Authorization:Basic OjgzNzY4MDc3NzA5MDE0NDM3MzE=' 
-d '' 
 

2024-03-24 17:16:21 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:b3p2ivXMHB9'. Project cannot be found by external id 'b3p2ivXMHB9'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m